### ISSUE TITLE
"x-terminal-emulator" not always available on the system

### ISSUE THREAD

**Issue by qmeeus** [brpaz/ulauncher-docker#3]
Whenever the extension is opening a terminal, it runs "x-terminal-emulator". In my case (opensuse leap), this resolves to nothing. 

Of course a quick workaround is to create a symlink that points 'x-terminal-emulator' to your preferred terminal emulator, for example:
```ln -s $(which tilix) /usr/local/x-terminal-emulator```

Nevertheless, there should be an option in the settings to specify your preferred app, or even a check at install to verify that something answers to that name in the path, and if not, take action to solve the problem... If no action is taken, this should be documented somewhere (hence this issue)

**Comment by brpaz** [comment]
Should be fixed now. I tested with Tilix and Gnome Terminal. You can select your preferred terminal on the extension preferences.
