### ISSUE TITLE
I cant add unexpected api 

### ISSUE THREAD

**Issue by anibalardid** [brpaz/ulauncher-docker#5]
Hi, this is the error when I tried to add to my ulauncher 4.4.0 rc1 (ubuntu 18.04)

 Unexpected API error. HTTPError:
Cancel
Add

**Comment by brpaz** [comment]
Please check: https://ulauncher-extension-doesnt-install-and-now.netlify.app/ and confirm that you have all the required python extensions.

But I am affraid that you are also using an old Ulauncher version. This extension was updated to Python 3 and Ulauncher V5.
