### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by antonio-petricca** [brpaz/ulauncher-docker#6]
Hi, it crashes on latest beta.

**Comment by dhollinger** [comment]
Looks like the latest `docker-py` update broke/changed a bunch of things. To get a container now in the `list_containers.py` file you have to replace line 25/26 with:

``` python
container = self.extension.docker_client.containers(filters: filters, limit: 8)
```

And that's not the only place I've seen the existing code break.

**Comment by dhollinger** [comment]
Found a temporary solution:

1. Uninstall `docker-py` and `docker` using `pip`: `pip3 uninstall docker docker-py`
2. Install the `docker` module (NOT `docker-py`): `pip3 install docker==3.7.2`
3. Restart Ulauncher 5.0beta
4. Docker extension should work now

I'll get a PR in for the README changes later tonight

**Comment by dhollinger** [comment]
@antonio-petricca There is a workaround detailed in the README file in PR #7
